name: 'Semantic Release Action'
description: 'GitHub Action for Semantic Release'
author: 'dmandrade'
branding:
  icon: 'package'
  color: 'orange'
inputs:
  plugins:
    description: 'Pre-install plugins'
    default: ''
outputs:
  published:
    description: 'Whether a new release was published'
  version:
    description: "Version of the new release"
runs:
  using: 'node12'
  main: 'index.js'
